version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    container_name: link_prediction_model
    command: uvicorn main:app --host 0.0.0.0 --port 4428 --workers 2
    ports:
      - "4428:4428"
    networks:
      - seq_backend

networks:
  seq_backend:
