version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    container_name: apt_prot_model
    command: uvicorn main:app --host 0.0.0.0 --port 4426 --workers 2
    ports:
      - "4426:4426"
    networks:
      - seq_backend

networks:
  seq_backend: