version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    container_name: apt_mol_model
    command: uvicorn main:app --host 0.0.0.0 --port 4431 --workers 2
    ports:
      - "4431:4431"
    networks:
      - seq_backend

networks:
  seq_backend: