version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: sequant_api
    command: uvicorn src.main:app --host 0.0.0.0 --port 5433 --workers 4
    ports:
      - "5899:5433"
    networks:
      - seq_backend

networks:
  seq_backend: