version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    container_name: nanobody_antigen_model
    command: uvicorn main:app --host 0.0.0.0 --port 4422 --workers 2
    ports:
      - "4422:4422"
    networks:
      - seq_backend

networks:
  seq_backend: