version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    container_name: similarity_calc
    command: uvicorn main:app --host 0.0.0.0 --port 4420 --workers 2
    ports:
      - "4420:4420"
    networks:
      - seq_backend

networks:
  seq_backend: